version: "3.9"
services:
  couchbase:
    build: deploy/couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    environment:
      COUCHBASE_INIT_DELAY_SECONDS: ${COUCHBASE_INIT_DELAY_SECONDS}
      COUCHBASE_ADMINISTRATOR_USERNAME: ${COUCHBASE_ADMINISTRATOR_USERNAME}
      COUCHBASE_ADMINISTRATOR_PASSWORD: ${COUCHBASE_ADMINISTRATOR_PASSWORD}

  redis:
    image: redis/redis-stack:latest
    ports:
      - 8001:8001
      - 6379:6379
  grog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      COUCHBASE_INIT_DELAY_SECONDS: ${COUCHBASE_INIT_DELAY_SECONDS}
      COUCHBASE_URL: ${COUCHBASE_URL}
      COUCHBASE_CLUSTER_NAME: ${COUCHBASE_CLUSTER_NAME}
      COUCHBASE_ADMINISTRATOR_USERNAME: ${COUCHBASE_ADMINISTRATOR_USERNAME}
      COUCHBASE_ADMINISTRATOR_PASSWORD: ${COUCHBASE_ADMINISTRATOR_PASSWORD}
      COUCHBASE_BUCKET_NAME: ${COUCHBASE_BUCKET_NAME}
      COUCHBASE_RBAC_USERNAME: ${COUCHBASE_RBAC_USERNAME}
      COUCHBASE_RBAC_PASSWORD: ${COUCHBASE_RBAC_PASSWORD}
      COUCHBASE_RBAC_NAME: ${COUCHBASE_RBAC_NAME}
      INIT_MAX_NUMBER_OF_RETRIES: ${INIT_MAX_NUMBER_OF_RETRIES}
      INIT_RETRY_BACKOFF_INTERVAL_MILLISECONDS: ${INIT_RETRY_BACKOFF_INTERVAL_MILLISECONDS}
      REDIS_URL: ${REDIS_URL}
      REDIS_DEFAULT_TTL_SECONDS: ${REDIS_DEFAULT_TTL_SECONDS}
    depends_on:
      - couchbase
      - redis
